import { lightTheme } from "thirdweb/react";

export const walletConnectTheme = lightTheme({
  colors: {
    accentButtonBg: "#1d4ed8",
    accentButtonText: "#ffffff",
    accentText: "#1d4ed8",
    borderColor: "#dbe4f0",
    connectedButtonBg: "#ffffff",
    connectedButtonBgHover: "#f8fafc",
    danger: "#dc2626",
    inputAutofillBg: "#eff6ff",
    modalBg: "#f8fbff",
    modalOverlayBg: "rgba(15, 23, 42, 0.24)",
    primaryButtonBg: "#0f172a",
    primaryButtonText: "#ffffff",
    primaryText: "#0f172a",
    scrollbarBg: "#dbeafe",
    secondaryButtonBg: "#eef4ff",
    secondaryButtonHoverBg: "#e0ecff",
    secondaryButtonText: "#0f172a",
    secondaryIconColor: "#64748b",
    secondaryIconHoverBg: "#e2e8f0",
    secondaryIconHoverColor: "#0f172a",
    secondaryText: "#526174",
    selectedTextBg: "#dbeafe",
    selectedTextColor: "#0f172a",
    separatorLine: "#dbe4f0",
    skeletonBg: "#dbeafe",
    success: "#15803d",
    tertiaryBg: "#edf4ff",
    tooltipBg: "#ffffff",
    tooltipText: "#0f172a",
  },
});
