import type { Metadata } from "next";
import { notFound } from "next/navigation";

import { FanletterAgentRankLedgerPage } from "@/components/fanletter-agentrank-ledger-page";
import {
  normalizeAgentRankCoverageAction,
  readFirstSearchParam,
} from "@/lib/agentrank/coverage-action";
import {
  agentRankReputationEventTypes,
  getFanletterAgentRankReputationEventFeed,
  type AgentRankReputationEventType,
} from "@/lib/agentrank/reputation-events";
import {
  filterAgentRankReputationEventFeedByMockScope,
  normalizeAgentRankEventMockScope,
  summarizeAgentRankEventMockScope,
} from "@/lib/agentrank/mock-events";
import { normalizeFanletterStarId } from "@/lib/fanletter-routing";
import { hasLocale, type Locale } from "@/lib/i18n";

export const dynamic = "force-dynamic";

type AgentRankLedgerSearchParams = {
  coverageAction?: string | string[];
  limit?: string | string[];
  memberEmail?: string | string[];
  scope?: string | string[];
  starId?: string | string[];
  type?: string | string[];
};

function readFirstParam(value?: string | string[]) {
  return readFirstSearchParam(value);
}

function normalizeLimit(value?: string | string[]) {
  const parsed = Number(readFirstParam(value));

  return Number.isFinite(parsed) ? Math.max(10, Math.min(parsed, 200)) : 120;
}

function normalizeMemberEmail(value?: string | string[]) {
  const normalized = readFirstParam(value)?.trim().toLowerCase();

  return normalized || null;
}

function normalizeEventType(
  value?: string | string[],
): AgentRankReputationEventType | null {
  const type = readFirstParam(value)?.trim();

  return type &&
    agentRankReputationEventTypes.includes(type as AgentRankReputationEventType)
    ? (type as AgentRankReputationEventType)
    : null;
}

function getLedgerMeta(locale: Locale) {
  if (locale === "ko") {
    return {
      description:
        "FanLetter에서 생성된 AgentRank Reputation Event를 운영자와 투자자가 검토하는 Ledger 페이지입니다.",
      title: "AgentRank Event Ledger | FanLetter",
    };
  }

  return {
    description:
      "An operator and investor ledger for reviewing AgentRank Reputation Events generated by FanLetter.",
    title: "AgentRank Event Ledger | FanLetter",
  };
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ lang: string }>;
}): Promise<Metadata> {
  const { lang } = await params;
  const locale = hasLocale(lang) ? lang : "ko";
  const meta = getLedgerMeta(locale);

  return {
    title: meta.title,
    description: meta.description,
    alternates: {
      canonical: `/${locale}/fanletter/agentrank/events`,
    },
    openGraph: {
      description: meta.description,
      siteName: "AIAVpark",
      title: meta.title,
      type: "website",
      url: `/${locale}/fanletter/agentrank/events`,
    },
    twitter: {
      card: "summary_large_image",
      description: meta.description,
      title: meta.title,
    },
  };
}

export default async function FanletterAgentRankLedgerRoute({
  params,
  searchParams,
}: {
  params: Promise<{ lang: string }>;
  searchParams: Promise<AgentRankLedgerSearchParams>;
}) {
  const [{ lang }, query] = await Promise.all([params, searchParams]);

  if (!hasLocale(lang)) {
    notFound();
  }

  const locale = lang as Locale;
  const starId = normalizeFanletterStarId(readFirstParam(query.starId) ?? null);
  const memberEmail = normalizeMemberEmail(query.memberEmail);
  const type = normalizeEventType(query.type);
  const limit = normalizeLimit(query.limit);
  const eventScope = normalizeAgentRankEventMockScope(
    readFirstParam(query.scope),
  );
  const coverageAction = normalizeAgentRankCoverageAction(query.coverageAction);
  const rawFeed = await getFanletterAgentRankReputationEventFeed({
    includeTypes: type ? [type] : undefined,
    limit,
    memberEmail,
    starId,
  });
  const feed = filterAgentRankReputationEventFeedByMockScope(
    rawFeed,
    eventScope,
  );

  return (
    <FanletterAgentRankLedgerPage
      coverageAction={
        coverageAction
          ? {
              action: coverageAction,
              memberEmail,
              starId,
            }
          : null
      }
      eventScope={{
        raw: summarizeAgentRankEventMockScope(rawFeed.events),
        scope: eventScope,
        scoped: summarizeAgentRankEventMockScope(feed.events),
      }}
      feed={feed}
      filters={{
        limit,
        memberEmail,
        scope: eventScope,
        starId,
        type,
      }}
      locale={locale}
    />
  );
}
